### ISSUE TITLE
Performance Benchmarks?

### ISSUE THREAD

**Issue by tuddman** [gorillalabs/neo4j-clj#10]
Great to see another Clojure + Neo4j project!

had you considered running any performance benchmarks against [hikari?](https://github.com/tomekw/hikari-cp)      or possibly integrating?

I got the bolt driver to work with hikari and anecdotally saw marked improvement over the initial neocons txs.

**Comment by chrisbetz** [comment]
Hi Scott,

don't know why I should incorporate hikari? The bolt driver has built-in connection pooling. Thus, I'd only add another layer of complexity. Same is true by adding JDBC, by the way. So, actually, by adding hikari there'd be two more layers of complexity - without any (obvious) gain.

Hope you can agree? Would like to close this issue.

Cheers,

Chris

**Comment by tuddman** [comment]
ahh. had forgotten bolt had the connection pooling,   Its been awhile since I implemented that.
