### ISSUE TITLE
extensible input conversion

### ISSUE THREAD

**Issue by mtkp** [gorillalabs/neo4j-clj#16]
it'd be nice to be able to have a hook to extend the input conversion function (such as via a multimethod in the compatibility namespace) to support different input types. at the moment i have to be sure to coerce every occurrence of certain types in my code that aren't supported by [Values/parameters](https://neo4j.com/docs/api/java-driver/current/org/neo4j/driver/v1/Values.html#parameters-java.lang.Object...-).

for example:

```clj
(defquery get-recent-users
  "MATCH (u:User) WHERE u.updatedAt >= $timestamp RETURN u")

(get-recent-users session {:timestamp (java.time.Instant/now)})
 ;;=> exception, unsupported type

(get-recent-users session {:timestamp (str (java.time.Instant/now))})
;; add `str` to fix it


;; but would be nice if...
(require '[neo4j-clj.compatibility :as compat])
(defmethod compat/clj->neo4j java.time.Instant [inst] (str inst))
(get-recent-users session {:timestamp (java.time.Instant/now)})
```

another option could be to provide a protocol, such as [`clojure.java.jdbc/ISQLValue`](https://github.com/clojure/java.jdbc/blob/master/src/main/clojure/clojure/java/jdbc.clj#L457). a protocol might have favorable performance characteristics to a multimethod.

thanks for sharing this library!

**Comment by chrisbetz** [comment]
Hi @mtkp,

thanks for the input. I thought about something like this also, but decided against a mechanism for that. The more systems and databases I came across, the more I think you should not hide the database under "abstractions" making things easier, but expose as much of the interface.

Timestamp is actually a pretty good example. Even within a single codebase, Timestamps might have different use-cases and contexts. Some are technical (like creation or modification time never exposed to end-users of your system), while others are exposed to users (like the publishing date of an article). Sometimes it is necessary to store the millisecond, sometimes it's not. Some need to be queried, others not.

If you query for timestamps (given they are not natively supported by Neo4j), you need to transform them into some format you could actually query, like a long. But you need to decide on a case-to-case basis.

In my opinion, each user of the library should be aware of the underlying database limitations and create his or her abstractions on top. You might want to create another layer of abstraction on top of neo4j-clj, but I don't want to include that functionality inside the thin wrapper neo4j-clj is.

Hope I could make the point in that compact form.

**Comment by mtkp** [comment]
wrapping neo4j-clj isn't hard and that's what i'll do. thanks for considering!
