### ISSUE TITLE
using connect with only url fails with AuthenticationException

### ISSUE THREAD

**Issue by MnRA** [gorillalabs/neo4j-clj#17]
The use case is that I prefer having the user/password/url all in one environment variable as opposed to 3.

the problem arises with neo4j-clj 2.0.1 and clojure 1.8

```clojure
;This way works fine
(db/connect "bolt://localhost:7687" "neo4j" "neo4j")
;=> {:url "bolt://localhost:7687",
; :user "neo4j",
; :password "neo4j",
; :db #object[org.neo4j.driver.internal.InternalDriver 0x40987523 ;"org.neo4j.driver.internal.InternalDriver@40987523"],
; :destroy-fn #object[neo4j_clj.core$connect$fn__6141 0x3ba43ccc ;"neo4j_clj.core$connect$fn__6141@3ba43ccc"]}

;This way not so much
(db/connect "bolt://neo4j:neo4j@localhost:7687")
;=> AuthenticationException Unsupported authentication token, scheme 'none' is only allowed when auth is disabled.  org.neo4j.driver.internal.util.Futures.blockingGet (Futures.java:122)
```
I'm not certain where the issue may lie, 
my best (and completely uninformed) guess is that ```(GraphDatabase/driver url config)``` on line 48 of the core is confusing config for auth (it's used ```(GraphDatabase/driver url auth config)``` on line 39).

**Comment by chrisbetz** [comment]
Yes, you're right. That's not possible because we decided to keep it as clean and simple as possible. That way, we're limiting some of the original drivers possibilities, but at the moment we need three different tokens, not one URL including the credentials. That's mainly because we - in our use case - change the URL only by environment (dev, stage, prod, etc.), but the credentials by user/system. I do not see a use case where having one URL brings additional benefit to make up for adding code/complexity.

**Comment by MnRA** [comment]
Ah ok, in that case, may I suggest adding a little bit of clarification in the comment on line 28?
`" You can connect using a url or a url, user, password combination."` to something like
`" You can connect using a url, user, password combination or url only (if the auth is disabled)."` 

I'm guessing it works without auth because of the error message and because if not these parts (lines 43 to 49) would be pointless: 

```clojure
;(...)
  ([url]
   (connect url nil))

  ([url options]
   (let [config (config options)
         db     (GraphDatabase/driver url config)]
     {:url url, :db db, :destroy-fn #(.close db)}))
;(...)
```

Thanks for the quick response!

**Comment by chrisbetz** [comment]
Super hint, will do. :)

MnRA <notifications@github.com> schrieb am Do., 7. März 2019, 14:44:
