### ISSUE TITLE
Support for 4.0.0 Neo4j

### ISSUE THREAD

**Issue by fhitchen** [gorillalabs/neo4j-clj#18]
Hi,
I pulled the latest docker image for neo4j and was unable to create a bolt connection, got some TLS handshake type error.

I realize that the docker image was for the 4.0.0 release and that the Clojure client is only 3.5.2. I upped the client version to the latest 3.5.14 and ran the tests and they all passed.

Then I tried to go to 4.0.0 and immediately hit errors in the compatibility.clj file with missing classes. It looks like the org.neo4j.driver.internal classes have been refactored away, maybe to driver.utils etc.

Do you have any plans to look at upgrading?

**Comment by chrisbetz** [comment]
Hi,

I just updated everything (at least I hope I found everything) to support Neo4j 4.0.0. You'll find stuff at clojars under [`[gorillalabs/neo4j-clj "4.0.1"]`](https://clojars.org/gorillalabs/neo4j-clj).

Happy hacking!

**Comment by fhitchen** [comment]
Hi,

Wow, thanks, that was quick. I'd only got as far as realizing I needed JDK
11 and that the v1 in the Neo4j driver needed to go. I also just learnt
what the #_ discard reader characters do.
regards, Francis.

**Comment by chrisbetz** [comment]
Hi @fhitchen,

hope you find everything ok, and yes, changes were not too bad. :)

Bye,

Chris
