### ISSUE TITLE
README shows incorrect db/connect usage

### ISSUE THREAD

**Issue by devth** [gorillalabs/neo4j-clj#20]
The uri param must be a `java.net.URI`, not a string.

```
class java.lang.String cannot be cast to class java.net.URI (java.lang.String and java.net.URI are in module java.base of loader 'bootstrap')
```

**Comment by san4d** [comment]
I'm facing the same issue. My attempted workaround is as follows:
```
(use '[clojure.java.io :only (as-url)])
(def db-url
    (as-url "bolt://localhost:7687"))
```
The code above throws the following error:
> Execution error (MalformedURLException) at java.net.URL/<init> (URL.java:652).
unknown protocol: bolt

**Comment by chrisbetz** [comment]
Hi @devth, @lgessler, @san4d ,

thanks for pointing this out and even contributing a workaround. I'm just getting back up from homeschooling, etc., so this took a while. Sorry for that. I changed it both in the README and the example project.

Keep on hacking :)
