### ISSUE TITLE
What is the reason for depending on the neo4j and neo4j-cypher?

### ISSUE THREAD

**Issue by yudistrange** [gorillalabs/neo4j-clj#23]
Hi,

The project.clj lists `neo4j` and `neo4j-cypher` as a dependencies as listed here: https://github.com/gorillalabs/neo4j-clj/blob/eb5d503ba6c8272c6cab32e39d89cbbd986dc954/project.clj#L13

What was the reason to include these?
These deps pull in a lot of transitive dependencies of their own, causing the start time of my clj app to increase from 5s to 150s 😝

**Comment by chrisbetz** [comment]
That's right and I'm on it. See #19 .

Thanks for pointing this out.

**Comment by chrisbetz** [comment]
Closed, please use version 4.1.0.
