### ISSUE TITLE
Documenting confusion over sessions/transactions

### ISSUE THREAD

**Issue by mathpunk** [gorillalabs/neo4j-clj#24]
Hi there! I'm trying out this library against a neo4j 4.2.0 enterprise version (which could be my problem, of course). I think I'm getting different results than your example code would suggest. As an example:

```
(db/defquery get-algorithms
  "CALL gds.list()")

(db/with-transaction local-db tx
  (first (get-algorithms tx)))
;; => {:name "gds.alpha.allShortestPaths.stream", :description "The All Pairs Shortest Path (APSP) calculates the shortest (weighted) path between all pairs of nodes.", :signature "gds.alpha.allShortestPaths.stream(graphName :: ANY?, configuration = {} :: MAP?) :: (sourceNodeId :: INTEGER?, targetNodeId :: INTEGER?, distance :: FLOAT?)", :type "procedure"}

(db/with-transaction local-db tx
  (take 1 (get-algorithms tx)))

Error printing return value (ResultConsumedException) at org.neo4j.driver.internal.util.Futures/blockingGet (Futures.java:143).
Cannot access records on this result any more as the result has already been consumed or the query runner where the result is created has already been closed.
```

Do you suppose this is a version problem? Am I doing something incorrectly?

**Comment by danielostling** [comment]
I have the same issue, but not when I run code in Emacs/Cider in the debug stepper. If I run it in the REPL without stepping, it fails just like @mathpunk describes.

**Comment by chrisbetz** [comment]
Hi, yeah, it's the same old lazyness thing. The sequence of results is realized only when printing stuff on the REPL (or in the debugger or whatever), which is outside of the scope of the result-set.

So, if you realize it using `doall` or in a way @danielostling is describing, this is not an issue anymore.

**Comment by mathpunk** [comment]
Thanks to you both. I've got to re-(re-re-)review why my mental model of laziness is off in an effectful context.
