### ISSUE TITLE
Possible glitch with/enhancement to db/with-transaction

### ISSUE THREAD

**Issue by ionse** [gorillalabs/neo4j-clj#27]
I believe there may be a missing conversion from neo4j float to java double in the case where one is not returning properties as opposed to nodes.  I've prepared an example (below) to illustrate. I'm running this on neo4j database version 4.2.4
=========== example code ============
(ns data.instruments
  (:require [neo4j-clj.core :as db])
  (:import [java.net URI])
  (:gen-class))

;; Seems something may be missing in neo4j-clj because
;; it doesn't seem to know how to treat a neo4j FloatValue as a Java Double
;;

;; First create a node (n:Test {s: "abc", d: 9.99}) via neo4j browser
;;
(db/defquery testq1
  "match (n:Test) return n.s as s, n.d as d")

(db/defquery testq2
  "match (n:Test) return n")

(defn testq []
  (println "testq1")
  (db/with-transaction init/local-db tx
    (let [recs (doall (testq1 tx))]
      (println (first recs))))

  (println "testq2")
  (db/with-transaction init/local-db tx
    (let [recs (doall (testq2 tx))]
      (println (:n (first recs))))))
;;
;; running testq produces the output below. Note that the 'd' property is
;; treated differently depending on the query style.
;;
;;
;; ops@ubuntu:~/prj/sbsm$ lein repl
;; 2021-03-23T14:12:49.729162 INFO Driver - Direct driver instance 2084863094 created for server address localhost:7687
;; nREPL server started on port 45103 on host 127.0.0.1 - nrepl://127.0.0.1:45103
;; REPL-y 0.4.3, nREPL 0.6.0
;; Clojure 1.10.0
;; OpenJDK 64-Bit Server VM 11.0.10+9-Ubuntu-0ubuntu1.20.04
;;     Docs: (doc function-name-here)
;;           (find-doc "part-of-name-here")
;;   Source: (source function-name-here)
;;  Javadoc: (javadoc java-object-or-class-here)
;;     Exit: Control+D or (exit) or (quit)
;;  Results: Stored in vars *1, *2, *3, an exception in *e

;; sbsm.core=> (inst/testq)
;; testq1
;; {:s abc, :d #object[org.neo4j.driver.internal.value.FloatValue 0x5a4980e2 9.99]}
;; testq2
;; {:d 9.99, :s abc}
;; nil
;; sbsm.core=>
============ example code ends ==============

**Comment by chrisbetz** [comment]
Pushed 4.1.2 to Clojars, see https://clojars.org/gorillalabs/neo4j-clj

**Comment by ionse** [comment]
It's fixed! Many Thanks / Danke
