### ISSUE TITLE
org.neo4j.driver.internal.value.FloatValue  isn't handled in neo4j->clj

### ISSUE THREAD

**Issue by tuddman** [gorillalabs/neo4j-clj#28]
please include `org.neo4j.driver.internal.value.FloatValue` into `compability.clj`  as a handled type in `neo4j->clj` with a `(.asDouble v)`     otherwise it throws a LossyCoercion Error

also, the ns with  `s/compability/compatibility`

**Comment by chrisbetz** [comment]
Sure. Thx!

**Comment by chrisbetz** [comment]
Pushed 4.1.2 to Clojars, see https://clojars.org/gorillalabs/neo4j-clj
